= AAR TP7 : Spring Boot
Frédéric Moal <frederic.moal@univ-orleans.fr>
v2.0, 2018-11-06: nouveau sujet
ifndef::imagesdir[:imagesdir: ../images]
ifndef::sourcedir[:sourcedir: ../../java]
ifndef::resourcesdir[:resourcesdir: ../../resources]


== Pré-requis

* Rappel des pré-requis

** MySQL doit être lancé sur localhost, avec une database banque existante.

** avec docker :
[source,bash]
docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 -d mysql

** Client Mysql avec docker :
[source,bash]
docker run -it --link mysql:mysql --rm mysql sh -c 'exec mysql -h"$MYSQL_PORT_3306_TCP_ADDR" -P"$MYSQL_PORT_3306_TCP_PORT" -uroot -p"$MYSQL_ENV_MYSQL_ROOT_PASSWORD"'


== Full annotation avec Spring Boot

Le but est de mettre en place une architecture complète (BD MySQL, JPA, DAO, service)
ainsi qu'un front Web sécurisé par Spring Security.

=== Le service Banque en Spring Boot

Refaire la même application [cd TP 6] en mode Spring Boot en utilisant Spring data jpa.

* Utilisez Spring Initializr pour fabriquer un nouveau projet maven.

* Récupérez le code source de votre modèle

* Ajoutez des Reposity en utilisant Spring Data JPA

* Modifiez votre couche de service pour utiliser cette nouvelle DAO

* Ajoutez dans le fichier application.properties dans les ressources :
[source,properties]
spring.datasource.url=jdbc:mysql://localhost:3306/banque?useSSL=false
spring.datasource.username=root
spring.datasource.password=root

cf
https://spring.io/guides/gs/accessing-data-jpa/


=== Un front web pour l'application

* Ajoutez une couche web [Thymeleaf] sur cette application
. Déplacer les classes précédentes dans un package `backend`
. Ajouter un nouveau package `frontend` dans lequel vous ajouterez
un controleur Spring MVC pour les urls `/clients`
. Ajoutez un formulaire statique permettant de saisir le no d'un client
. Ajoutez une page affichant un client et la liste de ses comptes,

* Comme il est assez délicat de trouver le no généré pour un client,
. Ajoutez une page statique d'accueil qui redirigera (automatiquement) vers la page de sélection d'un client en passant
par le contrôleur
. Ajoutez une page contenant un formulaire permettant de sélectionner à l'aide d'une liste déroulante un client enregistré en base
. Ajoutez une page affichant un client (et la liste de ses comptes),
renvoyé par le controleur à partir du no passé en paramètre par le formulaire précédent

cf https://spring.io/guides/gs/serving-web-content/

=== Activation de Spring Security

* Activez Spring Security dans le projet

* Configurez le projet pour stocker les utilisateurs dans la BD MySQL

Les utilisateurs seront ici les clients, qui pourront se connecter ;
il faut donc ajouter des informations dans l'entité Client pour permettre de gérer les connections :
[source,java]
----
	private String password;
	private boolean active;
	@ElementCollection(fetch = EAGER)
	@CollectionTable(name = "client_roles")
	private Set<String> roles;
----

On ajoute une configuration WebSecurityConfig pour définir la source
d'authentification comme étant une jdbcAuthentication.

Il va falloir stocker les clients avec leur mot de passe encodé dans la base ;
on ajoute un Bean dans WebSecurityConfig pour le faire dans la couche de service :
[source,java]
----
    @Bean
    public PasswordEncoder encoder() {
        return new BCryptPasswordEncoder();
    }
----
Cet encoder sera utilisé par jdbcAuthentication et par la couche de service au moment de l'enregistrement des clients.
